apiVersion: v1
kind: Service
metadata:
  name: project-step4
  labels: 
    version: v1
spec:
  type: NodePort
  selector:
    name: project-step4
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 1234
      targetPort: 80
