apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-step7-pvc
spec:
  storageClassName: project-step7-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi