apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-1-log-output
  labels:
    app: src-1-log-output
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-1-log-output
  template:
    metadata:
      name: src-1-log-output
      labels:
        app: src-1-log-output
        version: 1.0.0
    spec:
      volumes:
        - name: persisting-data-pvc
          persistentVolumeClaim: 
            claimName: persisting-data-pvc
      containers:
        - name: src-1-log-output
          image: src-1-log-output:v1
          volumeMounts:
            - name: persisting-data-pvc
              mountPath: /usr/src/mount
          env:
            - name: PERSISTENT_PONG_COUNT_PATH
              value: "/usr/src/mount/count.txt"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-2-pingpong
  labels:
    app: src-2-pingpong
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-2-pingpong
  template:
    metadata:
      name: src-2-pingpong
      labels:
        app: src-2-pingpong
        version: 1.0.0
    spec:
      volumes:
        - name: persisting-data-pvc
          persistentVolumeClaim: 
            claimName: persisting-data-pvc
      containers:
        - name: src-2-pingpong
          image: src-2-pingpong:v1
          volumeMounts:
            - name: persisting-data-pvc
              mountPath: /usr/src/mount
          env:
            - name: PERSISTENT_PONG_COUNT_PATH
              value: "/usr/src/mount/count.txt"