apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-step11
  namespace: project
  labels:
    name: project-step11
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-step11
  template:
    metadata:
      name: project-step11
      labels:
        name: project-step11
        version: v1
    spec:
      containers:
        - name: project-step11
          image: project-step11:v1
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: PROJECT_PORT
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: TODO_BACKEND_URL
            - name: DAILY_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DAILY_IMAGE_URL
