apiVersion: v1
kind: Service
metadata:
  name: project-step11
  namespace: project
spec:
  type: ClusterIP
  selector:
    name: project-step11
  ports:
    - name: http
      port: 1234
      targetPort: 80
