# HTTPRoute to split traffic between greeter v1 (75%) and v2 (25%)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeter-traffic-split
  namespace: exercises
spec:
  parentRefs:
    - name: src-3-greeter
      kind: Service
      group: ""
  rules:
    - backendRefs:
        - name: src-3-greeter-v1
          port: 80
          weight: 75
        - name: src-3-greeter-v2
          port: 80
          weight: 25
