apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummy-site-rolebinding
subjects:
- kind: ServiceAccount
  name: dummy-site-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: dummy-site-role
  apiGroup: rbac.authorization.k8s.io
