apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dummy-sites.dwk.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dwk.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                dummy_port:
                  type: integer
                replicas:
                  type: integer
                  default: 1
              required:
                - website_url
                - dummy_port
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.website_url
        - name: Port
          type: integer
          jsonPath: .spec.dummy_port
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: dummy-sites
    # singular name to be used as an alias on the CLI and for display
    singular: dummy-site
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DummySite
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dsite
