apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-step10-pvc
  namespace: project
spec:
  storageClassName: project-step10-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
