apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-step8-pvc
spec:
  storageClassName: project-step8-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
