apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-step14
  namespace: project
  labels:
    name: project-step14
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-step14
  template:
    metadata:
      name: project-step14
      labels:
        name: project-step14
        version: v1
    spec:
      containers:
        - name: project-step14
          image: todo-app-image
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: PROJECT_PORT
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: TODO_BACKEND_URL
            - name: DAILY_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DAILY_IMAGE_URL
