apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
  namespace: project
  labels:
    app: todo-broadcaster
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: todo-broadcaster-image
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: NATS_URL
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: BROADCASTER_WEBHOOK_URL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
