apiVersion: v1
kind: Service 
metadata:
  name: even-more-services
  labels:
    app: even-more-services
    version: v1
spec:
  type: NodePort
  selector:
    app: even-more-services
  ports:
    - name: main
      nodePort: 30002
      port: 1234
      targetPort: 8000
  