apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-step9-pvc
  namespace: project
spec:
  storageClassName: project-step9-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
