apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persisting-data-ingress
  labels:
    app.kubernetes.io/name: persisting-data-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: src-1-log-output
                port:
                  number: 1234
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: src-2-pingpong
                port:
                  number: 1234

