apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: more-services-ingress
  labels:
    app: more-services-ingress
    version: v1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: service-1-log-hash
                port:
                  number: 1234
          - path: /pingpong
            pathType: Prefix
            backend:
              service: 
                name: service-2-ping-pong
                port:
                  number: 1234


          
