apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: project
spec:
  clusterIP: None
  selector:
    app: postgres-db
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
