apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-1-log-output
  namespace: exercises
  labels:
    app: src-1-log-output
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-1-log-output
  template:
    metadata:
      name: src-1-log-output
      labels:
        app: src-1-log-output
        version: 1.0.0
    spec:
      containers:
        - name: src-1-log-output
          image: src-1-log-output:v1
          env:
            - name: PINGPONG_SERVICE_NAME
              value: "src-2-pingpong"
            - name: PINGPONG_SERVICE_PORT
              value: "1234"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-2-pingpong
  namespace: exercises
  labels:
    app: src-2-pingpong
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-2-pingpong
  template:
    metadata:
      name: src-2-pingpong
      labels:
        app: src-2-pingpong
        version: 1.0.0
    spec:
      containers:
        - name: src-2-pingpong
          image: src-2-pingpong:v1
