name: Delete Project NS

on:
  delete:

jobs:
  delete-environment:
    if: github.event.ref_type == 'branch'
    name: Delete Project NS
    runs-on: self-hosted

    steps:
      - name: Validate Branch
        run: |
          if [ "${{ github.event.ref }}" == "main" ]; then
            echo "Error: Cannot delete production environment (main branch)."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'kubectl'

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ secrets.GKE_CLUSTER }}'
          project_id: '${{ secrets.GKE_PROJECT }}'
          location: '${{ secrets.GKE_ZONE }}'

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Delete Namespace
        run: |-
          NAMESPACE="${{ github.event.ref }}"
          echo "Deleting namespace $NAMESPACE..."
          kubectl delete namespace $NAMESPACE || echo "Namespace $NAMESPACE not found or already deleted."
